# Generated by Django 6.0.5 on 2026-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_keyword', models.CharField(help_text='Palabra en español que identifica al objeto (debe coincidir con TRADUCCION_OBJETOS en camara_inteligente/services.py).', max_length=50)),
                ('frase_plantilla', models.TextField(help_text='Frase completa que el estudiante leerá en voz alta.')),
                ('nivel_dificultad', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('recompensa_monedas', models.PositiveIntegerField(default=5, help_text='Monedas otorgadas al pronunciar correctamente esta frase.')),
            ],
            options={
                'verbose_name': 'Frase de cámara inteligente',
                'verbose_name_plural': 'Frases de cámara inteligente',
                'ordering': ['objeto_keyword', 'nivel_dificultad'],
            },
        ),
    ]
