# Generated by Django 6.0.5 on 2026-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_inteligente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasetemplate',
            name='objeto_keyword',
            field=models.CharField(help_text='Palabra en español que identifica al objeto. Usada solo como respaldo de emergencia si Azure OpenAI falla (ver TRADUCCION_OBJETOS en camara_inteligente/services.py); no es el límite real de vocabulario.', max_length=50),
        ),
    ]
