# Generated by Django 6.0.5 on 2026-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_inteligente', '0002_alter_frasetemplate_objeto_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasetemplate',
            name='frase_plantilla',
            field=models.TextField(help_text='Trabalenguas de respaldo que el estudiante leerá en voz alta cuando Azure OpenAI no pudo generar uno (ver generar_objeto_y_trabalengua_llm en camara_inteligente/services.py).'),
        ),
    ]
