# Generated by Django 6.0.5 on 2026-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_inteligente', '0003_alter_frasetemplate_frase_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasetemplate',
            name='frase_plantilla',
            field=models.TextField(help_text='Frase de respaldo que el estudiante leerá en voz alta cuando Azure OpenAI no pudo generar una (ver _generar_frase_llm en camara_inteligente/services.py).'),
        ),
    ]
