# Generated by Django 6.0.5 on 2026-06-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara_inteligente', '0004_alter_frasetemplate_frase_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_economico', models.BooleanField(default=False, help_text='Si está activo, la Cámara Inteligente deja de llamar a Azure OpenAI por completo: traduce el objeto solo con el diccionario fijo, y usa únicamente frases ya guardadas (FraseTemplate) o, si no hay ninguna guardada para ese objeto, una frase mínima que solo pronuncia su nombre. Útil para cortar costos de IA sin apagar el módulo.')),
            ],
            options={
                'verbose_name': 'Configuración de cámara inteligente',
                'verbose_name_plural': 'Configuración de cámara inteligente',
            },
        ),
        migrations.AddField(
            model_name='frasetemplate',
            name='creada_automaticamente',
            field=models.BooleanField(default=False, help_text='True si esta fila fue guardada automáticamente a partir de una frase generada con éxito por el LLM (ver _guardar_frase_template_automatica en camara_inteligente/services.py), en vez de haber sido escrita a mano por el equipo docente.'),
        ),
        migrations.AlterField(
            model_name='frasetemplate',
            name='frase_plantilla',
            field=models.TextField(help_text='Frase que el estudiante leerá en voz alta.'),
        ),
        migrations.AlterField(
            model_name='frasetemplate',
            name='objeto_keyword',
            field=models.CharField(help_text='Palabra en español que identifica al objeto. Puede haber varias frases para el mismo objeto (se elige una al azar); se usan como respaldo si Azure OpenAI falla, o siempre que el "modo económico" esté activo (ver ConfiguracionCamara) para evitar llamadas al LLM.', max_length=50),
        ),
    ]
