# Generated by Django 6.0.5 on 2026-06-14 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_actividad', models.CharField(choices=[('nivel', 'Mapa de niveles'), ('historia', 'Historia interactiva'), ('desafio', 'Desafío diario'), ('camara', 'Cámara inteligente')], max_length=10)),
                ('zona', models.CharField(blank=True, choices=[('bosque_encantado', 'Bosque Encantado'), ('montana_letras', 'Montaña de las Letras'), ('valle_silabas', 'Valle de las Sílabas'), ('castillo_palabras', 'Castillo de las Palabras'), ('reino_lectura', 'Reino de la Lectura')], default='', max_length=20)),
                ('score', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
