# Generated by Django 6.0.5 on 2026-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='fecha',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('nivel', 'Mapa de niveles'), ('historia', 'Historia interactiva'), ('desafio', 'Desafío diario'), ('camara', 'Cámara inteligente')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='zona',
            field=models.CharField(blank=True, choices=[('bosque_encantado', 'Bosque Encantado'), ('montana_letras', 'Montaña de las Letras'), ('valle_silabas', 'Valle de las Sílabas'), ('castillo_palabras', 'Castillo de las Palabras'), ('reino_lectura', 'Reino de la Lectura')], db_index=True, default='', max_length=20),
        ),
    ]
