# Generated by Django 6.0.5 on 2026-06-11 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fuente', models.CharField(choices=[('OpenDyslexic', 'OpenDyslexic'), ('Lexend', 'Lexend'), ('Arial', 'Arial'), ('Verdana', 'Verdana')], default='Lexend', max_length=50)),
                ('tamano_fuente', models.CharField(choices=[('pequeno', 'Pequeño'), ('normal', 'Normal'), ('grande', 'Grande'), ('extra-grande', 'Extra Grande')], default='normal', max_length=20)),
                ('espaciado_letras', models.CharField(choices=[('normal', 'Normal'), ('medio', 'Medio'), ('amplio', 'Amplio')], default='normal', max_length=20)),
                ('espaciado_palabras', models.CharField(choices=[('normal', 'Normal'), ('medio', 'Medio'), ('amplio', 'Amplio')], default='normal', max_length=20)),
                ('tema_visual', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('infantil-azul', 'Infantil Azul'), ('infantil-verde', 'Infantil Verde')], default='infantil-azul', max_length=20)),
                ('velocidad_narracion', models.CharField(choices=[('lenta', 'Lenta'), ('normal', 'Normal'), ('rapida', 'Rápida')], default='normal', max_length=10)),
                ('tipo_voz', models.CharField(choices=[('nino', 'Niño'), ('nina', 'Niña'), ('adulto-masculino', 'Adulto Masculino'), ('adulto-femenino', 'Adulto Femenino')], default='nino', max_length=20)),
                ('volumen_narracion', models.IntegerField(default=80)),
                ('volumen_musica', models.IntegerField(default=50)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
    ]
