# Generated by Django 6.0.5 on 2026-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='motor_voz',
            field=models.CharField(choices=[('navegador', 'Navegador (rápido)'), ('azure', 'Voz natural (IA)')], default='navegador', max_length=10),
        ),
    ]
