# Generated by Django 6.0.5 on 2026-06-14 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveles', '0004_datos_zona_mapa_aventura'),
        ('recompensas', '0002_alter_tipoinsignia_criterio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_narrativa_actual', models.TextField(blank=True, default='', help_text='Texto narrativo del día. Si se deja vacío, se calcula automáticamente según la zona activa.')),
                ('zona_activa', models.CharField(choices=[('bosque_encantado', 'Bosque Encantado'), ('montana_letras', 'Montaña de las Letras'), ('valle_silabas', 'Valle de las Sílabas'), ('castillo_palabras', 'Castillo de las Palabras'), ('reino_lectura', 'Reino de la Lectura')], default='bosque_encantado', max_length=20)),
                ('palabras_meta_hoy', models.PositiveSmallIntegerField(default=5)),
                ('recompensa_monedas_base', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Configuración del desafío diario',
                'verbose_name_plural': 'Configuración del desafío diario',
            },
        ),
        migrations.CreateModel(
            name='DesafioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('recompensa_monedas', models.PositiveIntegerField(default=10)),
                ('ejercicios_obligatorios', models.ManyToManyField(blank=True, related_name='desafios_obligatorios', to='niveles.misionvocabulario')),
                ('ejercicios_opcionales', models.ManyToManyField(blank=True, related_name='desafios_opcionales', to='niveles.misionvocabulario')),
                ('recompensa_coleccionable', models.ForeignKey(blank=True, help_text='Coleccionable a otorgar al completar este desafío. Si se deja vacío, se elige uno al azar entre los que el usuario aún no tenga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios_diarios', to='recompensas.coleccionable')),
            ],
            options={
                'verbose_name': 'Desafío diario',
                'verbose_name_plural': 'Desafíos diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('monedas_ganadas', models.PositiveIntegerField(default=0)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='desafio.desafiodiario')),
                ('ejercicios_completados', models.ManyToManyField(blank=True, related_name='progresos_desafio', to='niveles.misionvocabulario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_desafio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de desafío diario',
                'verbose_name_plural': 'Progresos de desafío diario',
                'unique_together': {('usuario', 'desafio')},
            },
        ),
    ]
