# Generated by Django 6.0.5 on 2026-06-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
        ('niveles', '0009_seed_zonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafiodiario',
            name='ejercicios_obligatorios',
            field=models.ManyToManyField(blank=True, help_text='Override editorial opcional, compartido por todos los estudiantes. Si se deja vacío (caso normal), cada estudiante recibe ejercicios elegidos automáticamente según su propio nivel (ver desafio/services.py::_obtener_ejercicios_desafio).', related_name='desafios_obligatorios', to='niveles.misionvocabulario'),
        ),
        migrations.AlterField(
            model_name='desafiodiario',
            name='ejercicios_opcionales',
            field=models.ManyToManyField(blank=True, help_text='Override editorial opcional, compartido por todos los estudiantes. Si se deja vacío (caso normal), cada estudiante recibe ejercicios elegidos automáticamente según su propio nivel (ver desafio/services.py::_obtener_ejercicios_desafio).', related_name='desafios_opcionales', to='niveles.misionvocabulario'),
        ),
    ]
