# Generated by Django 6.0.5 on 2026-06-11 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('cabello', 'Cabello'), ('ropa', 'Ropa'), ('accesorio', 'Accesorio'), ('mascota', 'Mascota'), ('mueble', 'Mueble'), ('decoracion', 'Decoración'), ('trofeo', 'Trofeo')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar/items/')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReaccionAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('PRONUNCIACION_CORRECTA', 'Pronunciación Correcta'), ('PRONUNCIACION_INCORRECTA', 'Pronunciación Incorrecta'), ('OBJETO_RECONOCIDO', 'Objeto Reconocido'), ('OBJETO_NO_RECONOCIDO', 'Objeto No Reconocido'), ('HISTORIA_COMPLETADA', 'Historia Completada'), ('NIVEL_COMPLETADO', 'Nivel Completado'), ('LOGRO_DESBLOQUEADO', 'Logro Desbloqueado'), ('ERROR_CONEXION', 'Error de Conexión'), ('ERROR_CARGA', 'Error de Carga'), ('RECOMPENSA_GANADA', 'Recompensa Ganada')], max_length=50, unique=True)),
                ('emocion', models.CharField(choices=[('neutral', 'Neutral'), ('feliz', 'Feliz'), ('triste', 'Triste'), ('celebrando', 'Celebrando'), ('pensando', 'Pensando'), ('sorprendido', 'Sorprendido'), ('preocupado', 'Preocupado'), ('analizando', 'Analizando'), ('explicando', 'Explicando')], default='feliz', max_length=20)),
                ('mensaje', models.TextField(help_text='Mensaje que dirá el avatar ante este evento.')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_avatar', models.CharField(default='Mi Amigo', max_length=50)),
                ('nivel_visual', models.IntegerField(default=1)),
                ('estado_actual', models.CharField(choices=[('neutral', 'Neutral'), ('feliz', 'Feliz'), ('triste', 'Triste'), ('celebrando', 'Celebrando'), ('pensando', 'Pensando'), ('sorprendido', 'Sorprendido'), ('preocupado', 'Preocupado'), ('analizando', 'Analizando'), ('explicando', 'Explicando')], default='neutral', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueado', models.BooleanField(default=True)),
                ('equipado', models.BooleanField(default=False)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='avatar.avatar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.item')),
            ],
            options={
                'unique_together': {('avatar', 'item')},
            },
        ),
    ]
