# Generated by Django 6.0.5 on 2026-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('cabello', 'Cabello'), ('ropa_superior', 'Ropa Superior'), ('ropa_inferior', 'Ropa Inferior'), ('calzado', 'Calzado'), ('accesorio', 'Accesorio'), ('mascota', 'Mascota'), ('mueble', 'Mueble'), ('decoracion', 'Decoración'), ('trofeo', 'Trofeo')], max_length=20),
        ),
    ]
