# Generated by Django 6.0.5 on 2026-06-14 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_alter_item_categoria'),
        ('recompensas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='frase_bienvenida',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='avatar',
            name='personalidad',
            field=models.CharField(choices=[('animado', 'Animado'), ('tranquilo', 'Tranquilo'), ('gracioso', 'Gracioso')], default='animado', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='evento_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_avatar', to='recompensas.eventoespecial'),
        ),
        migrations.AddField(
            model_name='item',
            name='precio_monedas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('cabello', 'Cabello'), ('ropa_superior', 'Ropa Superior'), ('ropa_inferior', 'Ropa Inferior'), ('calzado', 'Calzado'), ('accesorio', 'Accesorio'), ('mascota', 'Mascota'), ('mueble', 'Mueble'), ('decoracion', 'Decoración'), ('trofeo', 'Trofeo'), ('habitacion', 'Habitación'), ('fondo', 'Fondo')], max_length=20),
        ),
        migrations.CreateModel(
            name='CasaAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alfombra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casas_con_alfombra', to='avatar.item')),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='avatar.avatar')),
                ('cama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casas_con_cama', to='avatar.item')),
                ('cuadro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casas_con_cuadro', to='avatar.item')),
                ('lampara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casas_con_lampara', to='avatar.item')),
            ],
        ),
    ]
