# Generated by Django 6.0.5 on 2026-06-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_avatar_frase_bienvenida_avatar_personalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manga_inf_der',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/items/mangas/'),
        ),
        migrations.AddField(
            model_name='item',
            name='manga_inf_izq',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/items/mangas/'),
        ),
        migrations.AddField(
            model_name='item',
            name='manga_sup_der',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/items/mangas/'),
        ),
        migrations.AddField(
            model_name='item',
            name='manga_sup_izq',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/items/mangas/'),
        ),
    ]
