# Generated by Django 6.0.5 on 2026-06-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_item_manga_inf_der_item_manga_inf_izq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaraAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('neutral', 'Neutral'), ('feliz', 'Feliz'), ('triste', 'Triste'), ('celebrando', 'Celebrando'), ('pensando', 'Pensando'), ('sorprendido', 'Sorprendido'), ('preocupado', 'Preocupado'), ('analizando', 'Analizando'), ('explicando', 'Explicando')], max_length=20, unique=True)),
                ('imagen', models.ImageField(upload_to='avatar/caras/')),
                ('imagen_parpadeo', models.ImageField(blank=True, null=True, upload_to='avatar/caras/')),
            ],
            options={
                'verbose_name': 'Cara del avatar',
                'verbose_name_plural': 'Caras del avatar',
                'ordering': ['estado'],
            },
        ),
    ]
