# Generated by Django 6.0.5 on 2026-06-25 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0005_caraavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('sombrero', 'Sombrero'), ('gafas', 'Gafas'), ('reloj', 'Reloj'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemColocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('mesa', 'Mesa'), ('estante', 'Estante de libros'), ('cama', 'Cama'), ('silla', 'Silla'), ('cuadro', 'Cuadro'), ('lampara', 'Lámpara'), ('alfombra', 'Alfombra')], max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_colocados', to='avatar.casaavatar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.item')),
            ],
            options={
                'unique_together': {('casa', 'slot')},
            },
        ),
    ]
