# Generated by Django 6.0.5 on 2026-06-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0007_migrar_items_casa_a_itemcolocado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casaavatar',
            name='alfombra',
        ),
        migrations.RemoveField(
            model_name='casaavatar',
            name='cama',
        ),
        migrations.RemoveField(
            model_name='casaavatar',
            name='cuadro',
        ),
        migrations.RemoveField(
            model_name='casaavatar',
            name='lampara',
        ),
    ]
