# Generated by Django 6.0.5 on 2026-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0008_eliminar_campos_viejos_casaavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaccionavatar',
            name='tipo_evento',
            field=models.CharField(choices=[('PRONUNCIACION_CORRECTA', 'Pronunciación Correcta'), ('PRONUNCIACION_INCORRECTA', 'Pronunciación Incorrecta'), ('OBJETO_RECONOCIDO', 'Objeto Reconocido'), ('OBJETO_NO_RECONOCIDO', 'Objeto No Reconocido'), ('HISTORIA_COMPLETADA', 'Historia Completada'), ('NIVEL_COMPLETADO', 'Nivel Completado'), ('LOGRO_DESBLOQUEADO', 'Logro Desbloqueado'), ('ERROR_CONEXION', 'Error de Conexión'), ('ERROR_CARGA', 'Error de Carga'), ('RECOMPENSA_GANADA', 'Recompensa Ganada'), ('BIENVENIDA_DIARIA', 'Bienvenida Diaria'), ('RACHA_ACTIVA', 'Racha Activa'), ('INSIGNIA_NUEVA', 'Insignia Nueva'), ('DESAFIO_COMPLETADO', 'Desafío Completado')], max_length=50, unique=True),
        ),
    ]
