# Generated by Django 6.0.5 on 2026-06-14 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='historias/portadas/')),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('nivel_dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Media'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('duracion_estimada_minutos', models.PositiveSmallIntegerField(default=5)),
                ('recompensa_monedas', models.PositiveIntegerField(default=15, help_text='Monedas otorgadas al completar esta historia.')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden del carrusel. Determina también el desbloqueo secuencial: una historia se desbloquea al completar la anterior en este orden.')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FragmentoHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto_narracion', models.TextField()),
                ('audio_narracion', models.FileField(blank=True, null=True, upload_to='historias/audios/')),
                ('pregunta_interactiva', models.TextField(blank=True)),
                ('tipo_respuesta', models.CharField(blank=True, choices=[('', 'Sin pregunta (solo narración)'), ('pronunciar', 'Pronunciar'), ('escribir', 'Escribir'), ('elegir', 'Elegir opción')], default='', max_length=10)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='historias.historia')),
            ],
            options={
                'verbose_name': 'Fragmento de historia',
                'verbose_name_plural': 'Fragmentos de historia',
                'ordering': ['historia', 'orden'],
                'unique_together': {('historia', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('fragmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='historias.fragmentohistoria')),
                ('fragmento_siguiente', models.ForeignKey(blank=True, help_text='Si se define, responder esta opción lleva a este fragmento (ramificación). Si se deja vacío, se avanza al siguiente fragmento por orden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_que_llevan_aqui', to='historias.fragmentohistoria')),
            ],
            options={
                'verbose_name': 'Opción de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
            },
        ),
        migrations.CreateModel(
            name='ProgresoHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fragmento_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='historias.fragmentohistoria')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='historias.historia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_historia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de historia',
                'verbose_name_plural': 'Progresos de historia',
                'unique_together': {('usuario', 'historia')},
            },
        ),
    ]
