# Generated by Django 6.0.5 on 2026-06-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras_clave', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fragmento_actual', models.PositiveIntegerField(default=0, help_text='Orden del fragmento en curso (control de progreso simplificado, sin FK).')),
                ('completada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia generada',
                'verbose_name_plural': 'Historias generadas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FragmentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('texto_narracion', models.TextField()),
                ('pregunta_interactiva', models.TextField(blank=True)),
                ('tipo_respuesta', models.CharField(blank=True, choices=[('', 'Sin pregunta (solo narración)'), ('pronunciar', 'Pronunciar'), ('escribir', 'Escribir'), ('elegir', 'Elegir opción')], default='', max_length=10)),
                ('historia_generada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='historias.historiagenerada')),
            ],
            options={
                'verbose_name': 'Fragmento generado',
                'verbose_name_plural': 'Fragmentos generados',
                'ordering': ['historia_generada', 'orden'],
                'unique_together': {('historia_generada', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='OpcionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('fragmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='historias.fragmentogenerado')),
            ],
            options={
                'verbose_name': 'Opción generada',
                'verbose_name_plural': 'Opciones generadas',
            },
        ),
    ]
