# Generated by Django 6.0.5 on 2026-06-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_historiagenerada_fragmentogenerado_opciongenerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentohistoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa que acompaña la narración de este fragmento.', null=True, upload_to='historias/fragmentos/'),
        ),
        migrations.AlterField(
            model_name='fragmentogenerado',
            name='tipo_respuesta',
            field=models.CharField(blank=True, choices=[('', 'Sin pregunta (solo narración)'), ('pronunciar', 'Pronunciar'), ('escribir', 'Escribir'), ('elegir', 'Elegir opción'), ('comprender', 'Comprensión libre (micrófono)')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fragmentohistoria',
            name='tipo_respuesta',
            field=models.CharField(blank=True, choices=[('', 'Sin pregunta (solo narración)'), ('pronunciar', 'Pronunciar'), ('escribir', 'Escribir'), ('elegir', 'Elegir opción'), ('comprender', 'Comprensión libre (micrófono)')], default='', max_length=10),
        ),
    ]
