# Generated by Django 6.0.5 on 2026-06-05 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos_recompensa', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='MisionVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_objetivo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('VOZ', 'Evaluación Fonética'), ('VISION', 'Reconocimiento de Objetos')], default='VOZ', max_length=10)),
                ('frase_historia', models.TextField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='niveles.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('nivel_actual', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niveles.nivel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
