# Generated by Django 6.0.5 on 2026-06-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0002_alter_progresoestudiante_nivel_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='narrativa_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nivel',
            name='orden_en_zona',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nivel',
            name='zona',
            field=models.CharField(choices=[('bosque_encantado', 'Bosque Encantado'), ('montana_letras', 'Montaña de las Letras'), ('valle_silabas', 'Valle de las Sílabas'), ('castillo_palabras', 'Castillo de las Palabras'), ('reino_lectura', 'Reino de la Lectura')], default='bosque_encantado', max_length=20),
        ),
    ]
