# Generated by Django 6.0.5 on 2026-06-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0005_datos_misiones_desafio_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='orden_en_zona',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
