# Generated by Django 6.0.5 on 2026-06-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0006_orden_en_zona_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mejores_estrellas', models.PositiveSmallIntegerField(default=0)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveles.nivel')),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_nivel', to='niveles.progresoestudiante')),
            ],
            options={
                'unique_together': {('progreso', 'nivel')},
            },
        ),
    ]
