# Generated by Django 6.0.5 on 2026-06-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0007_progresonivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('bosque_encantado', 'Bosque Encantado'), ('montana_letras', 'Montaña de las Letras'), ('valle_silabas', 'Valle de las Sílabas'), ('castillo_palabras', 'Castillo de las Palabras'), ('reino_lectura', 'Reino de la Lectura')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('cerrada', models.BooleanField(default=False, help_text='Si está marcada, no se pueden agregar niveles nuevos a esta zona.')),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['orden'],
            },
        ),
    ]
