# Generated by Django 6.0.5 on 2026-06-13 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccionable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('animal', 'Animal'), ('carta', 'Carta'), ('personaje', 'Personaje'), ('objeto_magico', 'Objeto Mágico')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/coleccionables/')),
                ('descripcion', models.TextField(blank=True)),
                ('precio_monedas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('navidad', 'Navidad'), ('halloween', 'Halloween'), ('vacaciones', 'Vacaciones')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('fondo_especial', models.ImageField(blank=True, null=True, upload_to='recompensas/eventos/')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('dragon', 'Dragón'), ('perro', 'Perro'), ('gato', 'Gato'), ('robot', 'Robot'), ('unicornio', 'Unicornio')], max_length=20)),
                ('imagen_base', models.ImageField(blank=True, null=True, upload_to='recompensas/mascotas/')),
                ('imagen_feliz', models.ImageField(blank=True, null=True, upload_to='recompensas/mascotas/')),
                ('imagen_triste', models.ImageField(blank=True, null=True, upload_to='recompensas/mascotas/')),
                ('precio_monedas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/insignias/')),
                ('criterio', models.CharField(choices=[('primer_nivel', 'Completar el primer nivel'), ('racha_7', 'Mantener una racha de 7 días'), ('racha_30', 'Mantener una racha de 30 días'), ('palabras_100', 'Acumular 100 puntos'), ('historias_10', 'Completar 10 historias'), ('nivel_5', 'Alcanzar el nivel 5'), ('nivel_10', 'Alcanzar el nivel 10')], max_length=30)),
                ('valor_umbral', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateTimeField(auto_now_add=True)),
                ('nivel_afecto', models.IntegerField(default=0)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recompensas.mascota')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascota_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('mostrada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
                ('tipo_insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recompensas.tipoinsignia')),
            ],
        ),
        migrations.CreateModel(
            name='ColeccionableUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('coleccionable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recompensas.coleccionable')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccionables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'coleccionable')},
            },
        ),
    ]
