# Generated by Django 6.0.5 on 2026-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recompensas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinsignia',
            name='criterio',
            field=models.CharField(choices=[('primer_nivel', 'Completar el primer nivel'), ('racha_7', 'Mantener una racha de 7 días'), ('racha_30', 'Mantener una racha de 30 días'), ('palabras_100', 'Acumular 100 puntos'), ('historias_10', 'Completar 10 historias'), ('nivel_5', 'Alcanzar el nivel 5'), ('nivel_10', 'Alcanzar el nivel 10'), ('desafio_diario', 'Completar un desafío diario')], max_length=30),
        ),
    ]
